### PR TITLE
Reject non-object specs

### PR DESCRIPTION
**Pull request by stefk**
Hi,

This is a port of https://github.com/facebook/react/pull/5628. It's basically just arg checking, to avoid wasting time debugging bad inputs. I hope you'll find that useful.

### CODE REVIEW

**Comment by kolodny** [comment]
I'm not sure how I feel about this part: `The spec may not contain an array except as the value of $set, $push, $unshift or $splice.` since it is possible that the function had `extend()` called with another spec type that accepts arrays

**Comment by stefk** [comment]
Would the following be ok?

> The spec may not contain an array except as the value of $set, $push, $unshift, $splice or any custom command allowing an array value.

**Comment by kolodny** [comment]
Yup, that works

**Comment by stefk** [comment]
Updated.

**Comment by kolodny** [comment]
thanks!

**Pull request merged**
