### PR TITLE
fix($cjs): have a default export

### LINKED ISSUE #96: TypeScript error on update method:  TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/immutability-helper/index"' has no compatible call signatures.
I am currently getting the following issue:
 TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "~/node_modules/immutability-helper/index"' has no compatible call signatures.

This issue does not happen on the 2.6.4 version but as soon as the solution pulled in the 2.6.5 version i started getting this issue.
For now I have made the version constant at 2.6.4, but wanted to notify you about this issue.

Thanks.

### PR DESCRIPTION
**Pull request by andreiglingeanu**
Fixes #96

### CODE REVIEW

**Comment by atfzl** [comment]
tests can be added as well
```js
// test.js
...
describe('update', function() {

  describe('default export', function() {
    it('should equal update', function() {
      expect(update.default).toEqual(update);
    });
  });

  describe('$push', function() {
...
```

**Comment by andreiglingeanu** [comment]
Thanks!

**Review by kolodny — APPROVED** [review]

**Comment by kolodny** [comment]
If you want to push a release too just bump the version in this PR.

**Comment by andreiglingeanu** [comment]
Here it goes. I'll push a release sometimes soon.

Just pushed a new, `2.6.6` release.

**Pull request merged**
