### PR TITLE
Add support for updating nested objects inside `Map`s

### PR DESCRIPTION
**Pull request by adelgado**
This PR should fix the issues presented in #102 and #89 . Please let me know if you need me to change anything.

### CODE REVIEW

**Comment by kolodny** [comment]
Awesome, thanks!

**Comment by jinixx** [comment]
$toggle needs fixing for maps and sets as well.

**Comment by kolodny** [comment]
Seems to work already:

```js
    var state = new Map([
      ['mapKey', { banana: 'yellow', apple: ['red'], blueberry: 'purple', obj: {a:true} }]
    ]);

    var updatedState = update(state, {
      ['mapKey']: {
        apple: { $set: ['green', 'red'] },
        obj: {$toggle: ['a']}
      }
    });

    expect(updatedState).toEqual(
      new Map([
        [
          'mapKey',
          { banana: 'yellow', apple: ['green', 'red'], blueberry: 'purple', obj: {a:false} }
        ]
      ])
    );
```

**Comment by jinixx** [comment]
Oh, you are right, $toggle works now. Thanks guys!

**Comment by code-hunger** [comment]
It is great this PR fixes the mentioned issues, but when on TypeScript things still break at compile time. The test runs fine if I cast the Map() to `any`, otherwise I'm getting the following compile error:

> Argument of type '{ ['mapKey']: { apple: { $set: string[]; }; obj: { $toggle: string[]; }; }; }' is not assignable to parameter of type 'Spec<Map<string, { banana: string; apple: string[]; blueberry: string; obj: { a: boolean; }; }>, ...'.                                                    
>   Object literal may only specify known properties, and '['mapKey']' does not exist in type 'Spec<Map<string, { banana: string; apple: string[]; blueberry: string; obj: { a: boolean; }; }>, ...'.

I cannot imagine if and how hard it could be to implement this in TS, because it has to infer that the type of the key `['mapKey']` and then decide whether it matches the first template argument of `Map<KeyT, ValueT>`, a `string` by which the properties of the Map object itself are accessed (e.g. `map.size`), or neither.  
E.g., when `KeyT` is string, and you are `$set`ting a `"size"`, it is ambiguous whether you want to do `map.set('size', x)`, or `map.size = x`. It is clear you shouldn't be allowed to do the second one, but what about other properties of map?

If you do `["something"]: { $set: value }`, then what will happen? If we take the logical way, it should `map.set('something', value)`, but that onlly works for KeyT being a string. In other cases it should choose the second way, but this introduces inconsistency which might be undesirable. And if you do not, we're back to the previous problem with native Map props, with the added inconvenience of being unable to call `map.set()` with the `$set` shortcut at all.

**Pull request merged**
