### PR TITLE
Added $map default command

### PR DESCRIPTION
**Pull request by smithcyr**
Added the `$map` default command for the use case where you have an array of object which you want to modify using a spec.

### CODE REVIEW

**Comment by kolodny** [comment]
Hmm, I'm not sure how I feel about this since `Array.map` already returns a new array. Wouldn't this be better:

```js
const state = [{a: 1}, {a: 2}];
const updated = state.map(obj => update(obj, {a: num => num + 1}))
```

**Comment by smithcyr** [comment]
Not sure what the question is.
Of course the same behavior `{$map: spec}` provides can be achieved with apply -> map -> update. 
The use case I personally added it for was with changing properties of heavily nested one-to-many related objects. The spec became very verbose if I only used apply so `$map` is only for readability.

**Comment by kolodny** [comment]
I see. I'm not a fan of adding operators that can have drastic changes (like being called 10000s of times) without some explicitness. This also is calling `update` recursively which also feels weird. I'd suggest keeping this as an external command that's added to your `update` context:

```js
update.extend('$map', function(value, nextObject, spec, originalObject) {
  // invariantMap(nextObject, '$map');
  return nextObject.map(function(element) {
    return update(element, value);
  });
});

const obj = {a: [{b: 1}, {b: 2}]};
const newObj = update(obj, {a: {$map: {b: v => v + 1}}});
console.log(newObj); // => {a: [{b: 2}, {b: 3}]}
```

**Comment by smithcyr** [comment]
That's fine. I'm already using it as an external command but thought it too useful not to add. 
There are no other default commands which are iterative so I can see how map doesn't really fit.
The recursion though I don't really see an issue with as the `spec` for every recursed update call would be different. 
If you feel it doesn't fit with the direction you want the project to go then feel free to decline the pull request.

**Comment by kolodny** [comment]
I think I'll close it for now, if other folks feel strongly about it, we can revisit

**Pull request closed without merging**
